### ISSUE TITLE
`build.rs` failure to build

### ISSUE THREAD

**Issue by koutheir** [sanpii/lxc-rs#27]
Building a crate that depends on `lxc-sys` version 0.4 fails to build `lxc-sys`:

```plain
   Compiling lxc-sys v0.4.0
error: failed to run custom build command for `lxc-sys v0.4.0`

Caused by:
  process didn't exit successfully: `<...>/target/debug/build/lxc-sys-a10f4eb383d5e3d5/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=lxc

  --- stderr
  thread 'main' panicked at '"__mbstate_t_union_(unnamed_at_/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t_h_16_3)" is not a valid Ident', <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.60/src/fallback.rs:791:9
  stack backtrace:
     0:     0x55f3631ec9ba - std::backtrace_rs::backtrace::libunwind::trace::h9a6b80bbf328ba5d
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0x55f3631ec9ba - std::backtrace_rs::backtrace::trace_unsynchronized::hd162ec543a11886b
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x55f3631ec9ba - std::sys_common::backtrace::_print_fmt::h78a5099be12f51a6
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:65:5
     3:     0x55f3631ec9ba - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha1c5390454d74f71
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:44:22
     4:     0x55f363211b9f - core::fmt::write::h9ffde816c577717b
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/fmt/mod.rs:1254:17
     5:     0x55f3631e9a05 - std::io::Write::write_fmt::h88186074961638e4
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/io/mod.rs:1698:15
     6:     0x55f3631ec785 - std::sys_common::backtrace::_print::h184198273ed08d59
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:47:5
     7:     0x55f3631ec785 - std::sys_common::backtrace::print::h1b4d8e7add699453
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:34:9
     8:     0x55f3631ede2e - std::panicking::default_hook::{{closure}}::h393bcea75423915a
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:269:22
     9:     0x55f3631edbd5 - std::panicking::default_hook::h48c64f31d8b3fd03
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:288:9
    10:     0x55f3631ee38e - std::panicking::rust_panic_with_hook::hafdc493a79370062
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:691:13
    11:     0x55f3631ee289 - std::panicking::begin_panic_handler::{{closure}}::h0a64bc82e36bedc7
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
    12:     0x55f3631ece26 - std::sys_common::backtrace::__rust_end_short_backtrace::hc203444fb7416a16
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
    13:     0x55f3631edfe2 - rust_begin_unwind
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
    14:     0x55f362cba473 - core::panicking::panic_fmt::h0f6ef0178afce4f2
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
    15:     0x55f3631b333d - proc_macro2::fallback::validate_ident::h4bf2032304334b4e
                                 at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.60/src/fallback.rs:791:9
    16:     0x55f3631b310a - proc_macro2::fallback::Ident::_new::h4587d04db81e07c7
                                 at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.60/src/fallback.rs:733:9
    17:     0x55f3631b316c - proc_macro2::fallback::Ident::new::h4b367b9f59c15c5d
                                 at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.60/src/fallback.rs:743:9
    18:     0x55f36319ff17 - proc_macro2::imp::Ident::new::h46fa3fc47ae95636
                                 at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.60/src/wrapper.rs:673:50
    19:     0x55f3631af985 - proc_macro2::Ident::new::h43f1029e7bb333f4
                                 at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.60/src/lib.rs:954:21
    20:     0x55f362dec5b2 - bindgen::ir::context::BindgenContext::rust_ident_raw::he4dda1670746adb8
                                 at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/ir/context.rs:878:9
    21:     0x55f362dec227 - bindgen::ir::context::BindgenContext::rust_ident::h4ccd18860a8b9681
                                 at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/ir/context.rs:870:9
    22:     0x55f362d1134b - <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen::hf02ed22a707920a3
                                 at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:1731:31
    23:     0x55f362d6b4b1 - <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen::hfc32be39ce9b6b4a
                                 at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:806:39
    24:     0x55f362d3d9c7 - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::h3e703b4a0f3c5197
                                 at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:492:17
    25:     0x55f362d14f57 - <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen::hf02ed22a707920a3
                                 at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:2062:13
    26:     0x55f362d6b4b1 - <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen::hfc32be39ce9b6b4a
                                 at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:806:39
    27:     0x55f362d3d9c7 - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::h3e703b4a0f3c5197
                                 at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:492:17
    28:     0x55f362d8dc8d - <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::{{closure}}::h4b957e4156b7687b
                                 at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:515:21
    29:     0x55f362d3dcb6 - <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::h7ae58eb2231ef0ca
                                 at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:545:13
    30:     0x55f362d3d9a3 - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::h3e703b4a0f3c5197
                                 at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:483:17
    31:     0x55f362d9bc58 - bindgen::codegen::codegen::{{closure}}::h932f22e8b2934cff
                                 at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:4287:9
    32:     0x55f362deede2 - bindgen::ir::context::BindgenContext::gen::hb40684ac034fe8ab
                                 at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/ir/context.rs:1190:19
    33:     0x55f362d9acad - bindgen::codegen::codegen::h22486a12f9d2de67
                                 at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:4251:5
    34:     0x55f362dbff28 - bindgen::Bindings::generate::he782b3475638b404
                                 at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/lib.rs:2374:32
    35:     0x55f362dbcee9 - bindgen::Builder::generate::h591ad0f7aacb16e6
                                 at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/lib.rs:1478:9
    36:     0x55f362cbc83e - build_script_build::main::h6791fa767af19dab
                                 at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lxc-sys-0.4.0/build.rs:4:20
    37:     0x55f362cbcb8b - core::ops::function::FnOnce::call_once::hd4e46897092f349c
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
    38:     0x55f362cbb65e - std::sys_common::backtrace::__rust_begin_short_backtrace::hf8e1cdec87a8c749
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:134:18
    39:     0x55f362cbcb01 - std::rt::lang_start::{{closure}}::h7a96cd7f64cb5d85
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:166:18
    40:     0x55f3631e61fe - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb1327dc2ef3fecdf
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:287:13
    41:     0x55f3631e61fe - std::panicking::try::do_call::h4044173225fe83dd
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
    42:     0x55f3631e61fe - std::panicking::try::hd8a722c09d156a53
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
    43:     0x55f3631e61fe - std::panic::catch_unwind::hd2ca07971cf0119b
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
    44:     0x55f3631e61fe - std::rt::lang_start_internal::{{closure}}::h26d89d595cf47b70
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:48
    45:     0x55f3631e61fe - std::panicking::try::do_call::hf47aa1aa005e5f1a
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
    46:     0x55f3631e61fe - std::panicking::try::h73d246b2423eaf4e
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
    47:     0x55f3631e61fe - std::panic::catch_unwind::hbaaeae8f1b2f9915
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
    48:     0x55f3631e61fe - std::rt::lang_start_internal::h76f3e81e6b8f13f9
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:20
    49:     0x55f362cbcada - std::rt::lang_start::h3e2e6d69353f54cc
                                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:165:17
    50:     0x55f362cbca0e - main
    51:     0x7f35d36b918a - __libc_start_call_main
                                 at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    52:     0x7f35d36b9245 - __libc_start_main_impl
                                 at ./csu/../csu/libc-start.c:381:3
    53:     0x55f362cbabf1 - _start
    54:                0x0 - <unknown>
```

**Comment by sanpii** [comment]
I can’t reproduce this bug, can you provide more information. Which version of rust do you use ? A minimal Cargo.toml + Cargo.lock, …

**Comment by koutheir** [comment]
```bash
$ rustc --version
rustc 1.70.0 (90c541806 2023-05-31)
```

```bash
$ env RUST_BACKTRACE=1 cargo clippy --verbose --package xtask
...
   Compiling lxc-sys v0.4.0
     Running `<...>/target/debug/build/lxc-sys-5f8bb803ba033861/build-script-build`
error: failed to run custom build command for `lxc-sys v0.4.0`

Caused by:
  process didn't exit successfully: `<...>/target/debug/build/lxc-sys-5f8bb803ba033861/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=lxc

  --- stderr
  thread 'main' panicked at '"__mbstate_t_union_(unnamed_at_/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t_h_16_3)" is not a valid Ident', <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.59/src/fallback.rs:811:9
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
     1: core::panicking::panic_fmt
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
     2: proc_macro2::fallback::validate_ident
               at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.59/src/fallback.rs:811:9
     3: proc_macro2::fallback::Ident::_new
               at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.59/src/fallback.rs:753:9
     4: proc_macro2::fallback::Ident::new
               at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.59/src/fallback.rs:763:9
     5: proc_macro2::imp::Ident::new
               at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.59/src/wrapper.rs:689:50
     6: proc_macro2::Ident::new
               at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.59/src/lib.rs:975:21
     7: bindgen::ir::context::BindgenContext::rust_ident_raw
               at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/ir/context.rs:878:9
     8: bindgen::ir::context::BindgenContext::rust_ident
               at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/ir/context.rs:870:9
     9: <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen
               at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:1731:31
    10: <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen
               at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:806:39
    11: <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen
               at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:492:17
    12: <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen
               at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:2062:13
    13: <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen
               at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:806:39
    14: <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen
               at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:492:17
    15: <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::{{closure}}
               at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:515:21
    16: <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen
               at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:545:13
    17: <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen
               at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:483:17
    18: bindgen::codegen::codegen::{{closure}}
               at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:4287:9
    19: bindgen::ir::context::BindgenContext::gen
               at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/ir/context.rs:1190:19
    20: bindgen::codegen::codegen
               at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/codegen/mod.rs:4251:5
    21: bindgen::Bindings::generate
               at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/lib.rs:2374:32
    22: bindgen::Builder::generate
               at <...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.59.2/src/lib.rs:1478:9
    23: build_script_build::main
               at ./build.rs:4:20
    24: core::ops::function::FnOnce::call_once
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by sanpii** [comment]
It’s sound like an old bindgen bug, can you try with the git version?

**Comment by koutheir** [comment]
I fetched the sources and replaced the implementation of  `lxc-sys` by appending the following to `Cargo.toml`:

```toml
[patch.crates-io]
lxc-sys = { path = "lxc-sys" }
```

That *fixes* the issue, but that's a weird thing to need doing. The implementation on `crates.io` should work.

**Comment by sanpii** [comment]
You can also write:
```toml
[dependencies]
lxc-sys = { git = "https://github.com/sanpii/lxc-rs.git" }
```

It’s just to test my hypothesis: it’s probably an old bindgen bug already fixed. I am going to release a new version to fix that.

**Comment by koutheir** [comment]
Version `0.5` fixes the issue. Thank you!
